"""The effect of every CLI verb: what the command tree cannot say about it.

A verb's parameters are read off the live Typer tree; whether it reads,
mutates or creates, and which daemon routes it drives, is declared once
here. ``read`` means the verb writes no canonical record: it may print,
or write a local report, cache or rendered file. The verb catalog refuses a
tree that carries a verb this table does not classify, and a row the tree
no longer carries.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final, Literal

EffectClass = Literal["read", "mutate", "create"]


@dataclass(frozen=True, slots=True)
class VerbEffect:
    """What the command tree cannot say about one CLI verb.

    Attributes:
        effect_class: Whether the verb reads, mutates or creates.
        routes: The daemon routes it drives; empty for a local verb.
    """

    effect_class: EffectClass
    routes: tuple[str, ...] = ()


def _read(*routes: str) -> VerbEffect:
    return VerbEffect("read", routes)


def _mutate(*routes: str) -> VerbEffect:
    return VerbEffect("mutate", routes)


def _create(*routes: str) -> VerbEffect:
    return VerbEffect("create", routes)


#: The effect and routes of every CLI verb under the contract groups.
CLI_VERB_EFFECTS: Final[dict[str, VerbEffect]] = {
    "track retire": _mutate("domain.track.retire"),
    "track create": _create("domain.track.create"),
    "milestone activate": _mutate("domain.milestone.activate"),
    "milestone open-review": _mutate("domain.milestone.open_review"),
    "milestone accept": _mutate("domain.milestone.accept"),
    "milestone cancel": _mutate("domain.milestone.cancel"),
    "milestone create": _create("domain.milestone.create"),
    "milestone set-target": _mutate("domain.milestone.set_target"),
    "milestone close-legacy": _mutate("domain.legacy.advance"),
    "milestone cancel-legacy": _mutate("domain.legacy.advance"),
    "milestone open-approval": _create("runtime.delivery.open_acceptance_approval"),
    "milestone seal-approval": _mutate("runtime.delivery.seal_acceptance_approval"),
    "batch activate": _mutate("domain.batch.activate"),
    "batch ready": _mutate("domain.batch.ready"),
    "batch create": _create("domain.batch.create"),
    "batch merge": _mutate("domain.batch.merge"),
    "batch observe-merge": _mutate("domain.batch.observe_merge"),
    "batch complete": _mutate("domain.batch.complete"),
    "batch close-legacy": _mutate("domain.legacy.advance"),
    "batch integrate": _mutate(
        "runtime.delivery.assemble", "operation.submit", "runtime.delivery.integrate"
    ),
    "batch adopt-landed": _mutate("runtime.delivery.adopt_landed"),
    "batch label": _create("runtime.delivery.label_audit"),
    "batch reconcile": _mutate(
        "runtime.delivery.read_back_merge", "runtime.delivery.reconcile_merge"
    ),
    "task promote": _mutate("domain.task.promote"),
    "task demote": _mutate("domain.task.demote"),
    "task start": _mutate("domain.task.start"),
    "task create": _create("domain.task.create"),
    "task claim": _mutate("domain.task.claim"),
    "task release": _mutate("domain.task.release"),
    "task ready": _mutate("domain.task.ready"),
    "task complete": _mutate("domain.task.complete"),
    "task advance-legacy": _mutate("domain.legacy.advance"),
    "task submit": _create("runtime.candidate.submit"),
    "task seal": _mutate("runtime.candidate.report.bind"),
    "task prove": _mutate("operation.submit", "runtime.delivery.prove_task"),
    "task assess": _read("runtime.delivery.task_assessment"),
    "run create": _create("domain.run.create"),
    "run start": _mutate("domain.run.start"),
    "run finish": _mutate("domain.run.finish"),
    "run fail": _mutate("domain.run.fail"),
    "run report": _read(),
    "run interrupt": _create("runtime.run.control.request"),
    "run cancel": _create("runtime.run.control.request"),
    "run reconcile": _create("runtime.run.control.request"),
    "run pause-dispatch": _create("runtime.dispatch.control.request"),
    "run drain-dispatch": _create("runtime.dispatch.control.request"),
    "run resume-dispatch": _create("runtime.dispatch.control.request"),
    "release changelog": _read(),
    "release notes": _read(),
    "release observe": _mutate("release.observe_target"),
    "release show": _read("release.show"),
    "release readiness": _read("release.compute_readiness"),
    "release create": _create("release.create"),
    "release approve": _mutate("release.approve"),
    "release publish": _mutate("release.publish"),
    "release retry": _mutate("release.retry_target"),
    "release reconcile": _mutate("release.reconcile"),
    "release burn": _mutate("release.burn"),
    "release adopt": _mutate("release.adopt"),
    "release cancel": _mutate("release.cancel"),
    "release candidate": _create("release.candidate"),
    "release pipeline": _mutate(
        "release.create",
        "release.candidate",
        "release.compute_readiness",
        "release.approve",
        "release.publish",
        "release.observe_target",
        "release.reconcile",
        "release.advance_train",
    ),
    "release tag": _mutate(),
    "release preflight": _read(),
    "release receipts": _create("release.produce_receipts"),
    "release advance": _mutate("release.advance_train"),
    "release bind-regime": _create("runtime.regime.bind"),
    "release discharge-debt": _mutate("runtime.regime.discharge_debt"),
    "release train show": _read(),
    "campaign new": _create("runtime.campaign.start"),
    "campaign run": _mutate("runtime.campaign.run"),
    "campaign budget": _mutate("projection.campaign.view", "runtime.campaign.budget.set"),
    "campaign cancel": _mutate("projection.campaign.view", "runtime.campaign.close"),
    "action snooze": _mutate("runtime.pending_action.snooze"),
    "action assign": _mutate("runtime.pending_action.assign"),
    "action decide-permission": _mutate("runtime.permission.decide"),
    "action notice": _mutate("budget_notice.dispose"),
    "question open-decision": _create("runtime.question.open_decision"),
    "question answer": _mutate("runtime.question.answer_numbered"),
    "question reply": _mutate("runtime.question.answer"),
    "workspace registry-list": _read(),
    "workspace registry-status": _read(),
    "workspace add": _create("registry.workspace.create"),
    "workspace show": _read(),
    "workspace list": _read(),
    "workspace select": _mutate(),
    "workspace member add": _mutate("registry.workspace.update_membership"),
    "workspace member remove": _mutate("registry.workspace.update_membership"),
    "config get": _read(),
    "config set": _mutate("config.set_layer_value", "config.set_layer_values"),
    "config unset": _mutate("config.unset_layer_value", "config.set_layer_values"),
    "config validate": _read(),
    "config menu": _mutate("config.set_layer_value", "config.unset_layer_value"),
    "config profile enable": _mutate(),
    "daemon run": _mutate(),
    "daemon start": _mutate(),
    "daemon restart": _mutate("daemon.shutdown"),
    "daemon ping": _read("daemon.ping"),
    "daemon status": _read("daemon.status"),
    "daemon stop": _mutate("daemon.shutdown"),
    "daemon replay-wal": _mutate(),
    "daemon reclaim": _mutate(),
    "daemon logs": _read(),
    "daemon service-enable": _mutate(),
    "daemon service-disable": _mutate(),
    "daemon service-status": _read(),
    "memory list": _read(),
    "memory render-context": _read(),
    "memory view": _read(),
    "memory digest": _read(),
    "memory stale": _read(),
    "memory add": _create("memory.add"),
    "memory promote": _mutate("memory.promote", "memory.link"),
    "memory compact": _mutate(),
    "memory prune": _mutate("memory.prune"),
    "memory gc": _mutate("memory.gc"),
    "memory tier": _mutate("memory.tier"),
    "ui": _read(),
    "migrate": _mutate(),
    "migrate status": _read(),
    "migrate epoch2": _mutate(),
    "reflect run": _read(),
    "reflect show": _read(),
    "reflect export": _read(),
    "reflect serve": _read(),
    "reflect prune": _read(),
    "follow": _read(),
    "verbs": _read(),
    "plan show": _read(),
    "plan submit": _create("planning.plan_revision.submit"),
    "plan approve": _mutate("planning.plan_revision.approve"),
    "plan apply": _mutate("planning.plan_revision.apply"),
    "record append": _create("domain.record.append"),
    "record evidence": _create("runtime.delivery.record_evidence"),
    "claim check": _mutate("runtime.evidence.claim.check"),
    "claim attest": _mutate("runtime.evidence.claim.attest"),
    "repository create": _create("domain.repository.create"),
    "hook run": _mutate(),
    "hook dispatch": _mutate(),
    "hook agent-output": _mutate(),
    "hook path-leak-lint": _read(),
    "hook email-leak-lint": _read(),
    "hook log-format-lint": _read(),
    "hook eawf012-design-provenance": _read(),
    "hook eawf013-bracket-position": _read(),
    "hook eawf014-no-manual-wrap": _read(),
    "hook eawf015-ears-advisory": _read(),
    "hook eawf018-structure-smell": _read(),
    "hook sigil-totality": _read(),
    "hook eawf023-artifact-placement": _read(),
    "hook eawf026-settings-categories": _read(),
    "hook eawf027-citation-scope": _read(),
    "hook eawf028-brief-immutable": _read(),
    "hook eawf024-test-tier-contract": _read(),
    "hook eawf025-test-placement": _read(),
    "hook eawf016-title-clarity": _read(),
    "hook eawf017-inline-refs": _read(),
    "hook vale-prose": _read(),
    "hook validate-prose": _read(),
    "hook eawf002-log-key": _read(),
    "hook eawf003-logger-acquire": _read(),
    "hook eawf019-math-facets": _read(),
    "hook eawf010-module-length": _read(),
    "hook eawf011-cognitive-complexity": _read(),
    "hook plugin-doctor-drift": _read(),
    "plugin install": _create(),
    "plugin update": _mutate(),
    "plugin sync": _mutate(),
    "plugin doctor": _read(),
    "plugin package": _read(),
    "cc statusline": _read(),
    "cc statusline prewarm": _read(),
    "cc statusline install": _mutate(),
    "skill list": _read(),
    "skill render": _read(),
    "skill check-report": _read(),
    "skill run": _mutate(),
    "skill reconcile": _read(),
    "mcp add": _create("mcp.add"),
    "mcp install": _mutate("mcp.install"),
    "mcp update": _mutate("mcp.update"),
    "mcp remove": _mutate("mcp.remove"),
    "mcp grant": _create("mcp.grant"),
    "mcp revoke": _mutate("mcp.revoke"),
    "mcp list": _read(),
    "mcp run-config": _create(),
    "mcp serve": _read(),
    "completion show": _read(),
    "completion install": _mutate(),
    "session close": _mutate("state.session_close"),
    "session recover": _mutate("state.session_recover"),
    "worktree merge-back": _mutate("state.worktree_merge_back"),
    "worktree cleanup": _mutate("state.worktree_cleanup"),
    "worktree reconcile": _mutate("state.worktree_reconcile"),
    "wal status": _read(),
    "wal list": _read(),
    "wal show": _read(),
    "store compact": _mutate(),
    "init": _create(),
    "clone-repo": _create(),
    "repo init": _create(),
    "repo add": _mutate(),
    "repo register": _mutate(),
    "repo remove": _mutate(),
    "repo prune": _mutate(),
    "status": _read(),
    "validate": _read(),
    "doctor": _mutate(),
    "doc verify": _read(),
    "schema dump": _mutate(),
    "sync": _mutate(),
    "rules view": _read(),
    "rules migrate": _read(),
    "rules rollback": _mutate(),
    "profile new": _create(),
    "profile validate": _read(),
    "coauthor resolve": _read(),
    "pr render": _read(),
    "wiki render": _read(),
    "render-output": _read(),
    "impact": _read(),
    "metrics": _mutate("runtime.estimation.refit"),
    "why": _read(),
    "jury label": _mutate("jury.label"),
    "bench list": _read(),
    "bench run": _read(),
    "bench compare": _read(),
    "bench turn-cost": _read(),
    "bench fixture seed": _create(),
    "telemetry pricing-currency-check": _read(),
    "snapshot list": _read(),
    "snapshot update": _mutate(),
    "vfl approve": _mutate(),
    "backup create": _read(),
    "backup list": _read(),
    "backup prune": _read(),
    "backup restore": _mutate(),
    "help": _read(),
    "version": _read(),
    "scope-debug": _read(),
}


__all__ = ["CLI_VERB_EFFECTS", "EffectClass", "VerbEffect"]
