"""Integration tests for memory views regenerated by ``eawf sync``.

The wave plan calls for a five-test integration set covering:

1. sync regenerates ``.ea/artifacts/rendered/memory/<scope>.md`` from
   ``memory.jsonl``;
2. ``--dry-run`` does NOT write the views;
3. ``--check`` exits 4 when a view would change;
4. sync is idempotent — second invocation reports no view drift;
5. promoting a memory entry to an artifact then re-syncing flips the
   superseded entry out of the default view.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from eawf.surfaces.cli.app import app

runner = CliRunner()


def _seed_state(tmp_path: Path) -> Path:
    state_dir = tmp_path / ".ea"
    state_dir.mkdir(parents=True, exist_ok=True)
    state_path = state_dir / "state.json"
    body = {
        "schema_version": "1.0",
        "scope_kind": "repo",
        "urn": "urn:eawf:v1:state:QR",
        "updated_at": "2026-05-08T00:00:00Z",
        "project": {
            "code": "QR",
            "slug": "quant",
            "title": "Quant",
            "domains": ["quant"],
            "default_branch": "main",
            "status": "active",
            "repo_urn": "urn:eawf:v1:repo:QR",
        },
        "current": {
            "project_code": "QR",
            "track_id": None,
            "phase_id": None,
            "iter_id": None,
            "active_wave_ids": [],
            "active_session_ids": [],
        },
        "workspace": None,
        "phases": {},
        "iters": {},
        "waves": {},
        "artifacts": {},
        "agent_sessions": {
            "SES-test-01": {
                "id": "SES-test-01",
                "role": "executor",
                "runtime": "test",
                "scope_id": "QR",
                "status": "active",
                "claimed_wave_ids": [],
                "worktree_ids": [],
                "artifact_ids": [],
                "started_at": "2026-05-08T00:00:00Z",
                "ended_at": None,
                "summary": None,
            }
        },
        "plugins": {},
        "indexes": {},
    }
    state_path.write_text(json.dumps(body, indent=2), encoding="utf-8")
    return state_path


@pytest.fixture
def tmp_workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    state_path = _seed_state(tmp_path)
    monkeypatch.setenv("EA_STATE", str(state_path))
    monkeypatch.delenv("EA_LOCK_TIMEOUT", raising=False)
    return tmp_path


def _add_memory(*, scope: str, title: str, body: str = "body") -> str:
    res = runner.invoke(
        app,
        [
            "--json",
            "memory",
            "add",
            "--scope",
            scope,
            "--title",
            title,
            "--body",
            body,
        ],
    )
    assert res.exit_code == 0, res.output
    return json.loads(res.output)["id"]


@pytest.mark.integration
def test_sync_regenerates_markdown_views_from_jsonl(tmp_workspace: Path) -> None:
    _add_memory(scope="QR", title="rule")
    res = runner.invoke(app, ["--json", "sync", "--target", str(tmp_workspace)])
    assert res.exit_code == 0, res.output
    payload = json.loads(res.output)
    view_paths = [Path(p) for p in payload["memory_views_regenerated"]]
    assert len(view_paths) >= 2  # at least <scope>.md + _all.md
    qr_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "QR.md"
    all_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "_all.md"
    assert qr_view.exists()
    assert all_view.exists()
    assert "memory-view-QR" in qr_view.read_text(encoding="utf-8")


@pytest.mark.integration
def test_sync_dry_run_does_not_write_views(tmp_workspace: Path) -> None:
    _add_memory(scope="QR", title="rule")
    qr_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "QR.md"
    assert not qr_view.exists()
    res = runner.invoke(app, ["--json", "sync", "--target", str(tmp_workspace), "--dry-run"])
    assert res.exit_code == 0, res.output
    # Dry-run reports the would-write paths but does NOT touch the workspace.
    payload = json.loads(res.output)
    assert any("QR.md" in p for p in payload["memory_views_regenerated"])
    assert not qr_view.exists()


@pytest.mark.integration
def test_sync_check_exits_4_when_views_drift(tmp_workspace: Path) -> None:
    _add_memory(scope="QR", title="rule")
    # First write so we have a stable baseline.
    res = runner.invoke(app, ["sync", "--target", str(tmp_workspace)])
    assert res.exit_code == 0, res.output
    # Tamper: rewrite the view body so a re-render would change bytes.
    qr_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "QR.md"
    qr_view.write_text("hand-edited\n", encoding="utf-8")
    res = runner.invoke(app, ["--json", "sync", "--target", str(tmp_workspace), "--check"])
    # NOTE: ``sync.py`` still uses a raw ``typer.Exit(code=4)`` literal that
    # pre-dates the C05 § 5.3 0..5 cutover (W04). A follow-up wave migrates
    # the literal to the symbolic ``exit_codes.VALIDATION_ERROR`` constant.
    assert res.exit_code == 4, res.output


@pytest.mark.integration
def test_sync_idempotent_views_unchanged_on_second_run(tmp_workspace: Path) -> None:
    _add_memory(scope="QR", title="rule")
    runner.invoke(app, ["sync", "--target", str(tmp_workspace)])
    qr_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "QR.md"
    first = qr_view.read_bytes()
    runner.invoke(app, ["sync", "--target", str(tmp_workspace)])
    second = qr_view.read_bytes()
    assert first == second
    # And --check after a fresh sync reports no view drift.
    res = runner.invoke(app, ["--json", "sync", "--target", str(tmp_workspace), "--check"])
    assert res.exit_code == 0, res.output


@pytest.mark.integration
def test_promote_to_artifact_then_sync_excludes_promoted(tmp_workspace: Path) -> None:
    """Once memory is promoted to a Decision, the default view drops it."""
    # Seed a peer entry so QR.md still has at least one row to render.
    peer_id = _add_memory(scope="QR", title="peer")
    promoted_id = _add_memory(scope="QR", title="rule")
    promote = runner.invoke(
        app,
        [
            "--json",
            "memory",
            "promote",
            "--session",
            "SES-test-01",
            "--source",
            promoted_id,
            "--source-kind",
            "memory",
            "--to",
            "artifact",
            "--artifact-kind",
            "decision",
        ],
    )
    assert promote.exit_code == 0, promote.output
    artifact_id = json.loads(promote.output)["promoted_to_artifact_id"]
    assert artifact_id.startswith("DEC-")

    res = runner.invoke(app, ["sync", "--target", str(tmp_workspace)])
    assert res.exit_code == 0, res.output
    qr_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "QR.md"
    body = qr_view.read_text(encoding="utf-8")
    # The promoted (now SUPERSEDED) memory entry is excluded from the default
    # view; the peer entry remains.
    assert promoted_id not in body
    assert peer_id in body
