"""Integration tests for memory views regenerated by ``eawf sync``.

The notes live on an epoch-2 tree's memory ledger. The set covers:

1. sync regenerates ``.ea/artifacts/rendered/memory/<scope>.md`` from
   the memory ledger;
2. ``--dry-run`` does NOT write the views;
3. ``--check`` exits 4 when a view would change;
4. sync is idempotent — second invocation reports no view drift;
5. promoting a memory entry to an artifact then re-syncing flips the
   superseded entry out of the default view.
"""

from __future__ import annotations

import json
from collections.abc import Iterator
from datetime import UTC, datetime
from pathlib import Path

import pytest
from typer.testing import CliRunner

from eawf.kernel.store.ledger import LedgerRecord, append_ledger_record
from eawf.kernel.store.tiers import Epoch2Collection
from eawf.surfaces.cli import exit_codes
from eawf.surfaces.cli.app import app
from tests.integration._memory_native import decision_ledger, native_memory_tree

runner = CliRunner()


@pytest.fixture
def tmp_workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[Path]:
    for _state_path in native_memory_tree(tmp_path, monkeypatch):
        yield tmp_path


def _file_decision(state_path: Path, key: str) -> None:
    """Stand a decision on the decision ledger, as the decision verb leaves one."""
    append_ledger_record(
        decision_ledger(state_path),
        LedgerRecord(
            collection=Epoch2Collection.DECISION,
            record_key=key,
            status="active",
            recorded_at=datetime.now(UTC),
            payload={"key": key},
        ),
    )


def _add_memory(*, scope: str, title: str, body: str = "body") -> str:
    res = runner.invoke(
        app,
        [
            "--json",
            "memory",
            "add",
            "--scope",
            scope,
            "--title",
            title,
            "--body",
            body,
        ],
    )
    assert res.exit_code == 0, res.output
    return json.loads(res.output)["result"]["id"]


@pytest.mark.integration
def test_sync_regenerates_markdown_views_from_jsonl(tmp_workspace: Path) -> None:
    _add_memory(scope="QR", title="rule")
    res = runner.invoke(app, ["--json", "sync", "--target", str(tmp_workspace)])
    assert res.exit_code == 0, res.output
    payload = json.loads(res.output)
    view_paths = [Path(p) for p in payload["memory_views_regenerated"]]
    assert len(view_paths) >= 2  # at least <scope>.md + _all.md
    qr_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "QR.md"
    all_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "_all.md"
    assert qr_view.exists()
    assert all_view.exists()
    assert "memory-view-QR" in qr_view.read_text(encoding="utf-8")


@pytest.mark.integration
def test_sync_dry_run_does_not_write_views(tmp_workspace: Path) -> None:
    _add_memory(scope="QR", title="rule")
    qr_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "QR.md"
    assert not qr_view.exists()
    res = runner.invoke(app, ["--json", "sync", "--target", str(tmp_workspace), "--dry-run"])
    assert res.exit_code == 0, res.output
    # Dry-run reports the would-write paths but does NOT touch the workspace.
    payload = json.loads(res.output)
    assert any("QR.md" in p for p in payload["memory_views_regenerated"])
    assert not qr_view.exists()


@pytest.mark.integration
def test_sync_check_exits_4_when_views_drift(tmp_workspace: Path) -> None:
    _add_memory(scope="QR", title="rule")
    # First write so we have a stable baseline.
    res = runner.invoke(app, ["sync", "--target", str(tmp_workspace)])
    assert res.exit_code == 0, res.output
    # Tamper: rewrite the view body so a re-render would change bytes.
    qr_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "QR.md"
    qr_view.write_text("hand-edited\n", encoding="utf-8")
    res = runner.invoke(app, ["--json", "sync", "--target", str(tmp_workspace), "--check"])
    assert res.exit_code == exit_codes.VALIDATION_ERROR, res.output


@pytest.mark.integration
def test_sync_idempotent_views_unchanged_on_second_run(tmp_workspace: Path) -> None:
    _add_memory(scope="QR", title="rule")
    runner.invoke(app, ["sync", "--target", str(tmp_workspace)])
    qr_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "QR.md"
    first = qr_view.read_bytes()
    runner.invoke(app, ["sync", "--target", str(tmp_workspace)])
    second = qr_view.read_bytes()
    assert first == second
    # And --check after a fresh sync reports no view drift.
    res = runner.invoke(app, ["--json", "sync", "--target", str(tmp_workspace), "--check"])
    assert res.exit_code == 0, res.output


@pytest.mark.integration
def test_promote_to_artifact_then_sync_excludes_promoted(tmp_workspace: Path) -> None:
    """Once memory is promoted to a Decision, the default view drops it."""
    # Seed a peer entry so QR.md still has at least one row to render.
    peer_id = _add_memory(scope="QR", title="peer")
    promoted_id = _add_memory(scope="QR", title="rule")
    _file_decision(tmp_workspace / ".ea" / "state.json", "DEC-RULE")
    promote = runner.invoke(
        app,
        [
            "--json",
            "memory",
            "promote",
            "--session",
            "SES-test-01",
            "--source",
            promoted_id,
            "--source-kind",
            "memory",
            "--to",
            "artifact",
            "--artifact-kind",
            "decision",
            "--artifact-id",
            "DEC-RULE",
        ],
    )
    assert promote.exit_code == 0, promote.output
    assert json.loads(promote.output)["result"]["promoted_to_artifact_id"] == "DEC-RULE"

    res = runner.invoke(app, ["sync", "--target", str(tmp_workspace)])
    assert res.exit_code == 0, res.output
    qr_view = tmp_workspace / ".ea" / "artifacts" / "rendered" / "memory" / "QR.md"
    body = qr_view.read_text(encoding="utf-8")
    # The promoted (now SUPERSEDED) memory entry is excluded from the default
    # view; the peer entry remains.
    assert promoted_id not in body
    assert peer_id in body
