"""Where a generator may write, and where writing into is a defect.

A generated file that lands in a hand-authored directory is
indistinguishable from something a person wrote, right up until someone
edits it and the next run silently overwrites the edit. The directory is
the only signal a reader has, so it has to mean something: under
``.ea/`` a directory is either authored or generated, never both.

Two roots are declared generated. ``indexes/`` holds the derived offset
indexes over the ledgers, and ``artifacts/rendered/`` holds the rendered
markdown views. Both regenerate from committed inputs, so both are
excluded from version control, and both declare a bounded retention: a
cache whose size and age have no declared ceiling is a disk leak waiting
for the tree that grows fastest, and the bound is what a sweep would be
allowed to enforce.

The fence is :func:`guard_generated_write`, which every writer of
derived bytes calls before it opens the file. It answers with the root
the target belongs to, and raises when the target is hand-authored, sits
in no declared root, or escapes the state directory entirely.
"""

from __future__ import annotations

from pathlib import Path
from typing import Annotated, Final

from pydantic import BaseModel, ConfigDict, Field, field_validator


class GeneratedWriteError(ValueError):
    """A generator targeted a path no declared generated root covers."""


class GeneratedRetention(BaseModel):
    """The declared ceiling on what a generated root may accumulate.

    Both bounds are required and both are capped, so a root cannot
    declare an effectively unlimited cache by writing a large number.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    max_entries: Annotated[int, Field(gt=0, le=100_000)]
    max_age_days: Annotated[int, Field(gt=0, le=365)]


class GeneratedRoot(BaseModel):
    """One directory under the state dir that generated bytes may land in."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    relative_dir: Annotated[str, Field(min_length=1, max_length=100)]
    producer: Annotated[str, Field(min_length=1, max_length=120)]
    retention: GeneratedRetention

    @field_validator("relative_dir")
    @classmethod
    def _plain_relative_dir(cls, value: str) -> str:
        """Reject anything but a plain relative directory under the state dir.

        Args:
            value: The declared directory.

        Returns:
            The directory unchanged.

        Raises:
            ValueError: The directory is absolute, trailing-slashed,
                wildcarded, or walks upward.
        """
        if value.startswith("/") or value.endswith("/"):
            raise ValueError(f"generated root {value!r} must be a plain relative directory")
        if "*" in value or ".." in value.split("/"):
            raise ValueError(f"generated root {value!r} must not wildcard or walk upward")
        return value


#: The declared generated-output roots, relative to the state directory.
GENERATED_ROOTS: Final[tuple[GeneratedRoot, ...]] = (
    GeneratedRoot(
        relative_dir="indexes",
        producer="ledger offset index",
        retention=GeneratedRetention(max_entries=512, max_age_days=90),
    ),
    GeneratedRoot(
        relative_dir="artifacts/rendered",
        producer="rendered markdown views",
        retention=GeneratedRetention(max_entries=4096, max_age_days=90),
    ),
)

#: Directories under the state dir whose contents a person wrote. A
#: generator that targets one of these has picked the wrong destination,
#: and the write is refused rather than shadowing an authored file.
HAND_AUTHORED_DIRS: Final[frozenset[str]] = frozenset(
    {
        "artifacts/audits",
        "artifacts/decisions",
        "artifacts/evidence",
        "artifacts/hypotheses",
        "artifacts/incidents",
        "artifacts/plans",
        "artifacts/research",
        "artifacts/reviews",
        "bench",
        "profiles",
    }
)


def _relative_to_state_dir(state_path: Path, target: Path) -> str:
    """Return *target* as a posix path relative to the state directory.

    Args:
        state_path: Path to the tree's ``state.json``.
        target: The file a generator is about to write.

    Returns:
        The relative posix path.

    Raises:
        GeneratedWriteError: The target is outside the state directory.
    """
    state_dir = state_path.resolve().parent
    resolved = target.resolve()
    if not resolved.is_relative_to(state_dir):
        raise GeneratedWriteError(f"{target} is outside the state directory {state_dir}")
    return resolved.relative_to(state_dir).as_posix()


def generated_root_for(relative: str) -> GeneratedRoot | None:
    """Return the generated root *relative* sits under, or ``None``.

    Args:
        relative: A posix path relative to the state directory.

    Returns:
        The declared root, or ``None`` when no root covers the path.
    """
    for root in GENERATED_ROOTS:
        if relative.startswith(f"{root.relative_dir}/"):
            return root
    return None


def guard_generated_write(state_path: Path, target: Path) -> GeneratedRoot:
    """Return the declared generated root *target* belongs to.

    Args:
        state_path: Path to the tree's ``state.json``.
        target: The file a generator is about to write.

    Returns:
        The generated root that accepts the write, whose ``retention``
        bounds what the root may accumulate.

    Raises:
        GeneratedWriteError: The target escapes the state directory,
            lands in a hand-authored directory, or sits in no declared
            generated root.
    """
    relative = _relative_to_state_dir(state_path, target)
    for authored in sorted(HAND_AUTHORED_DIRS):
        if relative == authored or relative.startswith(f"{authored}/"):
            roots = ", ".join(root.relative_dir for root in GENERATED_ROOTS)
            raise GeneratedWriteError(
                f"{relative!r} is hand-authored; generated output belongs under {roots}"
            )
    root = generated_root_for(relative)
    if root is None:
        roots = ", ".join(item.relative_dir for item in GENERATED_ROOTS)
        raise GeneratedWriteError(f"{relative!r} is in no declared generated root ({roots})")
    return root


__all__ = [
    "GENERATED_ROOTS",
    "HAND_AUTHORED_DIRS",
    "GeneratedRetention",
    "GeneratedRoot",
    "GeneratedWriteError",
    "generated_root_for",
    "guard_generated_write",
]
