"""Generated bytes land in a declared root, never in an authored directory.

The fence is asserted from both sides. A generator aimed at a
hand-authored directory (or at no declared root at all, or outside the
state directory) raises, and the shipped derived-index writer -- the one
production generator under ``.ea/`` -- is proven to go through the fence
by pointing it at a tree and reading back where the bytes landed.

Retention is asserted as a declaration: every root names a positive,
capped ceiling on entries and age, so a root whose cache could grow
without limit fails at import rather than at a full disk.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import pytest
from pydantic import ValidationError

from eawf.kernel.store.commit_policy import CommitPolicy, classify_path
from eawf.kernel.store.generated import (
    GENERATED_ROOTS,
    HAND_AUTHORED_DIRS,
    GeneratedRetention,
    GeneratedRoot,
    GeneratedWriteError,
    generated_root_for,
    guard_generated_write,
)
from eawf.kernel.store.index import write_ledger_index
from eawf.kernel.store.ledger import LedgerRecord, append_ledger_record
from eawf.kernel.store.paths import index_path, ledger_path
from eawf.kernel.store.tiers import Epoch2Collection

pytestmark = pytest.mark.unit


@pytest.fixture
def state_path(tmp_path: Path) -> Path:
    """Return the ``state.json`` path of an empty state tree."""
    state_dir = tmp_path / ".ea"
    state_dir.mkdir()
    path = state_dir / "state.json"
    path.write_text("{}\n", encoding="utf-8")
    return path


def _seed_task_ledger(state_path: Path) -> None:
    """Append one line to the task ledger so its index has content."""
    append_ledger_record(
        ledger_path(state_path, Epoch2Collection.TASK),
        LedgerRecord(
            collection=Epoch2Collection.TASK,
            record_key="TSK-0001",
            status="COMPLETED",
            recorded_at=datetime(2026, 9, 10, 12, 0, tzinfo=UTC),
            payload={"intent": "seed"},
        ),
    )


# --- the declaration -------------------------------------------------------


def test_every_generated_root_declares_a_bounded_retention() -> None:
    assert GENERATED_ROOTS
    for root in GENERATED_ROOTS:
        assert root.retention.max_entries > 0
        assert root.retention.max_age_days > 0


def test_generated_retention_rejects_a_zero_bound() -> None:
    with pytest.raises(ValidationError):
        GeneratedRetention(max_entries=0, max_age_days=30)


def test_generated_retention_rejects_an_unbounded_age() -> None:
    with pytest.raises(ValidationError):
        GeneratedRetention(max_entries=10, max_age_days=10_000)


def test_generated_retention_rejects_a_missing_bound() -> None:
    with pytest.raises(ValidationError):
        GeneratedRetention(max_entries=10)  # type: ignore[call-arg]


def test_generated_root_forbids_an_unknown_field() -> None:
    with pytest.raises(ValidationError):
        GeneratedRoot(
            relative_dir="indexes",
            producer="p",
            retention=GeneratedRetention(max_entries=1, max_age_days=1),
            surprise=True,  # type: ignore[call-arg]
        )


@pytest.mark.parametrize("bad", ["/abs", "indexes/", "index*", "../escape"])
def test_generated_root_rejects_a_non_plain_directory(bad: str) -> None:
    with pytest.raises(ValidationError):
        GeneratedRoot(
            relative_dir=bad,
            producer="p",
            retention=GeneratedRetention(max_entries=1, max_age_days=1),
        )


def test_generated_roots_are_declared_not_committed() -> None:
    """The two declarations agree: generated output is never committed."""
    for root in GENERATED_ROOTS:
        row = classify_path(f".ea/{root.relative_dir}/probe.json")
        assert row.policy is CommitPolicy.NOT_COMMITTED, root.relative_dir


def test_hand_authored_dirs_do_not_overlap_a_generated_root() -> None:
    for authored in HAND_AUTHORED_DIRS:
        assert generated_root_for(f"{authored}/file.md") is None, authored


# --- the fence: refusals ---------------------------------------------------


def test_guard_refuses_a_hand_authored_directory(state_path: Path) -> None:
    target = state_path.parent / "artifacts" / "audits" / "2026-09-10-generated.md"
    with pytest.raises(GeneratedWriteError, match="hand-authored"):
        guard_generated_write(state_path, target)


def test_guard_refuses_the_hand_authored_directory_itself(state_path: Path) -> None:
    with pytest.raises(GeneratedWriteError, match="hand-authored"):
        guard_generated_write(state_path, state_path.parent / "profiles")


def test_guard_refuses_an_undeclared_directory(state_path: Path) -> None:
    with pytest.raises(GeneratedWriteError, match="no declared generated root"):
        guard_generated_write(state_path, state_path.parent / "scratch" / "out.json")


def test_guard_refuses_the_state_dir_root(state_path: Path) -> None:
    """The state dir itself is not a generated root, so a bare file is refused."""
    with pytest.raises(GeneratedWriteError, match="no declared generated root"):
        guard_generated_write(state_path, state_path.parent / "out.json")


def test_guard_refuses_a_path_outside_the_state_dir(state_path: Path, tmp_path: Path) -> None:
    with pytest.raises(GeneratedWriteError, match="outside the state directory"):
        guard_generated_write(state_path, tmp_path / "elsewhere.json")


def test_guard_refuses_an_upward_escape(state_path: Path) -> None:
    escape = state_path.parent / "indexes" / ".." / ".." / "loot.json"
    with pytest.raises(GeneratedWriteError, match="outside the state directory"):
        guard_generated_write(state_path, escape)


# --- the fence: acceptances ------------------------------------------------


def test_guard_accepts_the_index_root_with_bounded_retention(state_path: Path) -> None:
    root = guard_generated_write(state_path, state_path.parent / "indexes" / "task.index.json")
    assert root.relative_dir == "indexes"
    assert root.retention.max_entries > 0
    assert root.retention.max_age_days > 0


def test_guard_accepts_the_render_cache_root(state_path: Path) -> None:
    target = state_path.parent / "artifacts" / "rendered" / "memory" / "scope.md"
    root = guard_generated_write(state_path, target)
    assert root.relative_dir == "artifacts/rendered"


def test_guard_accepts_a_render_of_a_hand_authored_kind(state_path: Path) -> None:
    """``artifacts/rendered/research`` is generated; ``artifacts/research`` is not."""
    target = state_path.parent / "artifacts" / "rendered" / "research" / "brief.md"
    assert guard_generated_write(state_path, target).relative_dir == "artifacts/rendered"


# --- the shipped generator goes through the fence --------------------------


def test_write_ledger_index_lands_in_the_declared_root(state_path: Path) -> None:
    _seed_task_ledger(state_path)
    written_index = write_ledger_index(state_path, Epoch2Collection.TASK)
    assert written_index.line_count == 1

    written = index_path(state_path, Epoch2Collection.TASK)
    assert written.exists()
    assert guard_generated_write(state_path, written).relative_dir == "indexes"


def test_index_path_of_one_tree_is_foreign_to_another(state_path: Path, tmp_path: Path) -> None:
    """The fence is anchored on the state dir, not on the path's shape."""
    foreign = tmp_path / "other" / ".ea"
    foreign.mkdir(parents=True)
    (foreign / "state.json").write_text("{}\n", encoding="utf-8")
    with pytest.raises(GeneratedWriteError, match="outside the state directory"):
        guard_generated_write(foreign / "state.json", index_path(state_path, Epoch2Collection.TASK))
