"""Generated Markdown carries one line per paragraph, at the generator.

Rendered Markdown is not manually line-wrapped (``markdown-no-manual-wrap``,
enforced by EAWF014). A hand fix to a generated page does not hold: the next
``eawf doc verify`` or golden refresh reproduces the page from its source and
the wrap comes back. So the assertion belongs on the render, not on the bytes.

Two renderers are covered because both feed the strict prose gate:

- ``eawf.platform.docs.autogen`` -- the ``docs/reference/autogen/*.md`` pages,
  whose preambles are authored as Python string literals;
- ``eawf.surfaces.render.agents`` -- the ``.claude/agents/<role>.md`` bodies,
  which are hard-wrapped literals unwrapped at the render seam by
  :func:`~eawf.surfaces.render.unwrap.unwrap_markdown_paragraphs`.

The committed pages are checked against a live render too, so a page that was
regenerated by an older generator is caught rather than sitting stale.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from eawf.platform.docs import autogen
from eawf.platform.lint.eawf014_no_manual_wrap import check_source
from eawf.runtime.runtimes.claude.plugin_install import _render_agent
from eawf.surfaces.render.agents import AGENT_REGISTRY
from eawf.surfaces.render.unwrap import unwrap_markdown_paragraphs

pytestmark = pytest.mark.unit

_REPO_ROOT = Path(__file__).resolve().parents[2]


def _markdown_pages() -> list[autogen.GeneratedPage]:
    return [page for page in autogen.all_pages() if page.relpath.endswith(".md")]


@pytest.mark.parametrize("page", _markdown_pages(), ids=lambda p: Path(p.relpath).name)
def test_autogen_page_renders_unwrapped(page: autogen.GeneratedPage) -> None:
    """Every generated reference page emits one line per prose paragraph."""
    findings = check_source(page.body)
    assert not findings, (
        f"{page.relpath} renders manually wrapped prose; join the paragraph in "
        f"the generator literal, not in the rendered file:\n"
        + "\n".join(f"  {f.render()}" for f in findings)
    )


@pytest.mark.parametrize("page", _markdown_pages(), ids=lambda p: Path(p.relpath).name)
def test_autogen_page_on_disk_matches_the_generator(page: autogen.GeneratedPage) -> None:
    """The committed page is what today's generator produces."""
    dest = _REPO_ROOT / page.relpath
    assert dest.is_file(), f"{page.relpath} is missing from the tree"
    assert dest.read_text(encoding="utf-8") == page.body, (
        f"{page.relpath} drifted from its generator; regenerate the autogen pages"
    )


@pytest.mark.parametrize("spec", AGENT_REGISTRY, ids=lambda s: s.role)
def test_agent_body_renders_unwrapped(spec) -> None:
    """Every rendered agent body emits one line per prose paragraph."""
    findings = check_source(_render_agent(spec, {}))
    assert not findings, f"agent {spec.role!r} renders manually wrapped prose:\n" + "\n".join(
        f"  {f.render()}" for f in findings
    )


def test_unwrapper_reds_on_a_wrapped_paragraph() -> None:
    """The falsifier: the lint this gate leans on must fire on wrapped prose."""
    wrapped = "A paragraph that was hard wrapped by its author across\ntwo source lines.\n"
    assert check_source(wrapped), "EAWF014 no longer detects a wrapped paragraph"
    assert not check_source(unwrap_markdown_paragraphs(wrapped))


def test_unwrapper_preserves_structure_and_boundaries() -> None:
    """Empty, single-line, fenced, and list inputs survive the unwrapper."""
    assert unwrap_markdown_paragraphs("") == ""
    assert unwrap_markdown_paragraphs("One line.") == "One line."
    fenced = "```python\nx = 1\ny = 2\n```"
    assert unwrap_markdown_paragraphs(fenced) == fenced
    assert unwrap_markdown_paragraphs("# Heading\n\nBody.") == "# Heading\n\nBody."
    assert unwrap_markdown_paragraphs("- item one\n  continued\n- item two") == (
        "- item one continued\n- item two"
    )
    # A blank line is a paragraph boundary, not a join point.
    assert unwrap_markdown_paragraphs("first\n\nsecond") == "first\n\nsecond"


def test_unwrapper_rejects_a_non_string() -> None:
    """A non-string surface fails at the boundary rather than silently."""
    with pytest.raises(AttributeError):
        unwrap_markdown_paragraphs(None)  # type: ignore[arg-type]
